
name: ecommerce-temporal

services:

  postgres:

    image: postgres:18.6

    container_name: ecommerce-postgres

    environment:

      POSTGRES_DB: ecommerce

      POSTGRES_USER: user

      POSTGRES_PASSWORD: 1234

    ports:

      - "5432:5432"

    volumes:

      - ./infra/postgres/data:/var/lib/postgresql

    healthcheck:

      test: ["CMD-SHELL", "pg_isready -U user -d ecommerce"]

      interval: 5s

      timeout: 5s

      retries: 10


#volumes:
#
#  postgres-data:
