package com.market.ecommerce.order.application.service;

import com.market.ecommerce.order.application.port.in.CreateOrderUseCase;
import com.market.ecommerce.order.application.port.out.DomainEventOutbox;
import com.market.ecommerce.order.application.port.out.OrderRepository;
import com.market.ecommerce.order.application.port.out.ProductSnapshotProvider;
import com.market.ecommerce.order.domain.Order;
import com.market.ecommerce.order.domain.OrderId;
import com.market.ecommerce.order.domain.OrderItemCandidate;
import com.market.ecommerce.shared.domain.valueobjects.ProductId;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

@Service
public class CreateOrderService implements CreateOrderUseCase {

    private final OrderRepository orderRepository;

    private final ProductSnapshotProvider productSnapshotProvider;

    private final DomainEventOutbox domainEventOutbox;

    private final Clock clock;

    public CreateOrderService(
            OrderRepository orderRepository,
            ProductSnapshotProvider productSnapshotProvider,
            DomainEventOutbox domainEventOutbox,
            Clock clock) {
        this.orderRepository = orderRepository;
        this.productSnapshotProvider = productSnapshotProvider;
        this.domainEventOutbox = domainEventOutbox;
        this.clock = clock;
    }

    @Override
    @Transactional
    public Order create(Command command) {

        /*
         * First, we collect all the IDs.
         */

        Set<ProductId> productIds = command
                .items()
                .stream()
                .map(Item::productId)
                .collect(Collectors.toSet());

        /*
         * Queries the Catalog via a PORT.
         */

        Map<ProductId, ProductSnapshotProvider.ProductSnapshot> products = productSnapshotProvider
                .findPurchasableProducts(productIds);

        /*
         * If a product was not returned, it:
         *
         * - does not exist
         * OR
         * - is inactive.
         */

        for (ProductId productId : productIds) {

            if (!products.containsKey(productId)) {

                throw new IllegalArgumentException("Product is not available for purchase: " + productId.value());

            }

        }

        /*
         * Now we create candidates for the Aggregate.
         *
         * We still preserve duplicates here.
         *
         * If the request includes the same product twice,
         * the Aggregate will be responsible for rejecting it.
         */

        List<OrderItemCandidate> candidates = command.items()
                .stream()
                .map(requestItem -> {

                    var product = products.get(requestItem.productId());

                    return new OrderItemCandidate(
                            product.productId(),
                            product.name(),
                            product.unitPrice(),
                            requestItem.quantity()
                    );

                })
                .toList();

        Instant now = Instant.now(clock);

        Order order = Order.place(
                OrderId.newId(),
                command.customerId(),
                command.customerEmail(),
                candidates,
                now
        );

        /*
         * Insert order + items.
         */

        orderRepository.save(order);

        /*
         * Retrieves events generated by the Aggregate.
         */

        var events = order.pullDomainEvents();

        /*
         * Writes to the Outbox.
         *
         * Since we are within the same @Transactional scope,
         *
         * Order + Items + Outbox
         *
         * are committed or rolled back together.
         */

        domainEventOutbox.appendAll(events);

        return order;

    }

}
